// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameBackendClient is the client API for GameBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameBackendClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (GameBackend_StreamClient, error)
}

type gameBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewGameBackendClient(cc grpc.ClientConnInterface) GameBackendClient {
	return &gameBackendClient{cc}
}

func (c *gameBackendClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/proto.GameBackend/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameBackendClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GameBackend_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameBackend_ServiceDesc.Streams[0], "/proto.GameBackend/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameBackendStreamClient{stream}
	return x, nil
}

type GameBackend_StreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type gameBackendStreamClient struct {
	grpc.ClientStream
}

func (x *gameBackendStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameBackendStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameBackendServer is the server API for GameBackend service.
// All implementations must embed UnimplementedGameBackendServer
// for forward compatibility
type GameBackendServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Stream(GameBackend_StreamServer) error
	mustEmbedUnimplementedGameBackendServer()
}

// UnimplementedGameBackendServer must be embedded to have forward compatible implementations.
type UnimplementedGameBackendServer struct {
}

func (UnimplementedGameBackendServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGameBackendServer) Stream(GameBackend_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGameBackendServer) mustEmbedUnimplementedGameBackendServer() {}

// UnsafeGameBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameBackendServer will
// result in compilation errors.
type UnsafeGameBackendServer interface {
	mustEmbedUnimplementedGameBackendServer()
}

func RegisterGameBackendServer(s grpc.ServiceRegistrar, srv GameBackendServer) {
	s.RegisterService(&GameBackend_ServiceDesc, srv)
}

func _GameBackend_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameBackendServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameBackend/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameBackendServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameBackend_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameBackendServer).Stream(&gameBackendStreamServer{stream})
}

type GameBackend_StreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type gameBackendStreamServer struct {
	grpc.ServerStream
}

func (x *gameBackendStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameBackendStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameBackend_ServiceDesc is the grpc.ServiceDesc for GameBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GameBackend",
	HandlerType: (*GameBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _GameBackend_Connect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GameBackend_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/server.proto",
}
